name: build

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 17
          architecture: x64
          check-latest: true
          cache: npm
          cache-dependency-path: package.json
      - name: Install npm dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: gh-pages
      - name: Upload stats
        uses: actions/upload-artifact@v3
        with:
          name: build-stats
          path: stats.html